const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Sprite,
		C3.Plugins.Spritefont2,
		C3.Plugins.Arr,
		C3.Behaviors.solid,
		C3.Plugins.Browser,
		C3.Behaviors.Bullet,
		C3.Behaviors.Timer,
		C3.Behaviors.destroy,
		C3.Plugins.Text,
		C3.Behaviors.Fade,
		C3.Plugins.Audio,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Behaviors.Bullet.Cnds.CompareSpeed,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.Arr.Exps.IndexOf,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Cnds.Contains,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Text.Acts.SetAngle,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count,
		C3.ScriptsInEvents.EventoFase1_Event48_Act2,
		C3.ScriptsInEvents.EventoFase2_Event19_Act2,
		C3.ScriptsInEvents.EventoFase2_Event47_Act2,
		C3.ScriptsInEvents.EventoFase2_Event48_Act2
	];
};
self.C3_JsPropNameTable = [
	{PlanoDeFundoEmBlocos: 0},
	{Teclado: 0},
	{Mouse: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{btnJogar: 0},
	{leite: 0},
	{imagem: 0},
	{nomeDoJogo: 0},
	{nuvens: 0},
	{PlanoDeFundoEmBlocos3: 0},
	{FonteDeSprites: 0},
	{historia: 0},
	{btnVoltar: 0},
	{btnVamosJogar: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{aDir: 0},
	{leiteEspecial: 0},
	{Sólido: 0},
	{ParedeBloco: 0},
	{Navegador: 0},
	{TileSize: 0},
	{Score: 0},
	{Lives: 0},
	{playerRespawnTime: 0},
	{nbGhost: 0},
	{leiteEspecialScore: 0},
	{ghostEscapeTime: 0},
	{ghostBlinkTime: 0},
	{Alive: 0},
	{game: 0},
	{direction: 0},
	{moveDirection: 0},
	{name: 0},
	{vert: 0},
	{hor: 0},
	{eaten: 0},
	{escape: 0},
	{escapeBlink: 0},
	{Projétil: 0},
	{Cronômetro: 0},
	{DestruirForaDoLayout: 0},
	{Cães: 0},
	{ghostSpawn: 0},
	{ID: 0},
	{Playerlives: 0},
	{moveDuration: 0},
	{dirCharge: 0},
	{Milu: 0},
	{playerSpaw: 0},
	{Esmaecer: 0},
	{txtScore: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Áudio: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0}
];

self.InstanceType = {
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	Teclado: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	btnJogar: class extends self.ISpriteInstance {},
	leite: class extends self.ISpriteInstance {},
	imagem: class extends self.ISpriteInstance {},
	nomeDoJogo: class extends self.ISpriteInstance {},
	nuvens: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos3: class extends self.ITiledBackgroundInstance {},
	FonteDeSprites: class extends self.ISpriteFontInstance {},
	historia: class extends self.ISpriteInstance {},
	btnVoltar: class extends self.ISpriteInstance {},
	btnVamosJogar: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	aDir: class extends self.IArrayInstance {},
	leiteEspecial: class extends self.ISpriteInstance {},
	ParedeBloco: class extends self.ISpriteInstance {},
	Navegador: class extends self.IInstance {},
	game: class extends self.ISpriteInstance {},
	Cães: class extends self.ISpriteInstance {},
	ghostSpawn: class extends self.ISpriteInstance {},
	Playerlives: class extends self.ISpriteInstance {},
	Milu: class extends self.ISpriteInstance {},
	playerSpaw: class extends self.ISpriteInstance {},
	Score: class extends self.ITextInstance {},
	txtScore: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {}
}